package kr.co.onfilm.encodingworker.application;

public enum FailureCode {
    UNSUPPORTED_MESSAGE_SCHEMA,
    INVALID_REQUEST,
    SOURCE_NOT_FOUND,
    SOURCE_DOWNLOAD_FAILED,
    UNSUPPORTED_MEDIA,
    ENCODE_TIMEOUT,
    ENCODE_FAILED,
    OUTPUT_VALIDATION_FAILED,
    OUTPUT_UPLOAD_FAILED,
    CORE_API_UNAVAILABLE,
    UNEXPECTED_WORKER_ERROR
}
